---

- hosts: gluster4-servers
  strategy: free
  become: true
  tasks:
    - name: add gluster repo
      get_url:
        url: http://artifacts.ci.centos.org/gluster/nightly/master.repo
        dest: /etc/yum.repos.d/gluster-nightly-master.repo

    - name: Install GlusterFS Server
      yum:
        name: glusterfs-server
        state: present

    - name: Install GD2 built locally
      copy:
        remote_src: yes
        src: /vagrant/gd2/glusterd2
        dest: /usr/sbin/glusterd2
        mode: 0775

    - name: Remove required directories
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /etc/glusterd2
        - /usr/local/var/log/glusterd2
        - /usr/local/var/lib/glusterd2
        - /usr/local/var/run/glusterd2
        - /usr/local/etc/glusterd2

    - name: Create required directories
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - /etc/glusterd2
        - /usr/local/var/log/glusterd2
        - /usr/local/var/lib/glusterd2
        - /usr/local/var/run/glusterd2
        - /usr/local/etc/glusterd2

    - name: Install GD2 config file
      template:
        src: glusterd2.j2
        dest: /usr/local/etc/glusterd2/glusterd2.toml

    - name: Install GD2 service unit
      copy:
        src: glusterd2.service
        dest: /usr/lib/systemd/system/glusterd2.service

    - name: Enable GD2 service and start it
      systemd:
        name: glusterd2
        daemon_reload: yes
        state: restarted
        enabled: yes

...
